config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root "home#index"

  devise_for :users, path: "",
             path_names: { sign_in: :login, sign_out: :logout, registration: :users },
             controllers: {
               sessions: "users/sessions",
               registrations: "users/registrations",
               passwords: "users/passwords",
             }

  resources :links
  resources :tags
end

app/views/shared/_header.html.erb
<header class="p-3 bg-info text-white sticky-top">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to "Home", root_path, class: "nav-link px-2 text-white" %></li>
        <li><%= link_to "Link", links_path, class: "nav-link px-2 text-white" %></li>
        <li><%= link_to "Tag", tags_path, class: "nav-link px-2 text-white" %></li>
        <!--<li><a href="#" class="nav-link px-2 text-white">About</a></li>-->
      </ul>
      <div class="text-end">
        <% if user_signed_in? %>
          <%= link_to "로그아웃", destroy_user_session_path, class: "btn btn-outline-light me-2" %>
        <% else %>
          <%= link_to "로그인", new_user_session_path, class: "btn btn-outline-light me-2" %>
          <%= link_to "회원가입", new_user_registration_path, class: "btn btn-outline-warning" %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="alert alert-primary">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>