config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root "home#index"

  devise_for :users, path: "",
             path_names: { sign_in: :login, sign_out: :logout, registration: :users },
             controllers: {
               sessions: "users/sessions",
               registrations: "users/registrations",
               passwords: "users/passwords",
             }

  resources :links
  resources :tags
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user

  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings
  accepts_nested_attributes_for :taggings

  validates_presence_of :name, :url, :user
  validates_uniqueness_of :name, scope: :user_id
  validates_uniqueness_of :url, scope: :user_id
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_link, only: %i[ show edit update destroy ]

  # GET /links or /links.json
  def index
    @links = Link.includes(:tags).where(user_id: current_user.id)
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
    @link.taggings.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to links_path, notice: t('.notice')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    if @link.update(link_params)
      redirect_to links_path, notice: t('.notice')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy
    redirect_to links_url, notice: t('.notice')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def link_params
    params.require(:link).permit(:name, :url, :description, taggings_attributes: [:id, :tag_id, :_destroy])
          .merge(user: current_user)
  end
end

app/controllers/v1/links_controller.rb
class V1::LinksController < V1::ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = Link.new(link_params)
    respond_to do |format|
      if @link.save
        format.html { redirect_to links_path, notice: "링크 생성에 성공 했습니다." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to links_path, notice: "링크 수정에 성공 했습니다." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url, notice: "링크 삭제에 성공 했습니다." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def link_params
    params.require(:link).permit(:name, :url, :description).merge(user: current_user)
  end
end

app/views/links/_form.html.erb
<%= simple_form_for @link, html: { class: "col-md-6 col-sm-12 my-3" } do |f| %>
  <%= f.input :name, label: "이름" %>
  <%= f.input :url, label: "주소", placeholder: "http:://" %>
  <%= f.input :description, label: "설명" %>

  <% if current_user.tags.present? %>
    <%= f.simple_fields_for :taggings do |p| %>
      <%= p.input :tag_id, label: "분류", collection: current_user.tags, as: :radio_buttons,
                  item_label_class: "mx-2", item_wrapper_class: 'btn', include_hidden: false %>
    <% end %>
  <% else %>
    <%= link_to "분류 추가", new_tag_path, class: "btn btn-outline-primary mb-3" %>
  <% end %>

  <div>
    <%= link_to "목록으로 돌아가기", links_path, class: "btn btn-outline-secondary" %>
    <%= f.button :submit, "저장", class: "btn btn-outline-success" %>
  </div>

<% end %>

app/views/links/_link.html.erb
<div class="col">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">
        <%= link_to link.name, link.url, target: "_blank", class: "link-dark" %>
      </h5>
      <p class="card-text"><%= link.try(:description) %></p>
      <p>
        <% link.tags.each do |tag| %>
          <span class="badge text-light" style="background-color: <%= tag.color %>"><%= tag.name %></span>
        <% end %>
      </p>
      <%= link_to "링크 수정", edit_link_path(link), class: "btn btn-outline-warning" %>
      <%= link_to "링크 삭제", link, class: "btn btn-outline-danger", data: { "turbo-method": :delete, "turbo-confirm": "정말로 삭제 하시나요?" } %>
    </div>
  </div>
</div>

app/views/links/edit.html.erb
<h1 class="h3 my-3">링크 수정</h1>

<%= render "form", link: @link %>

app/views/links/index.html.erb
<%= link_to "링크 추가", new_link_path, class: "btn btn-outline-primary my-3" %>

<div class="row row-cols-1 row-cols-md-3 g-4 mb-3">
  <% @links.each do |link| %>
    <%= render link %>
  <% end %>
</div>

app/views/links/new.html.erb
<h1 class="h3 my-3">링크 생성</h1>

<%= render "form", link: @link %>

app/views/links/show.html.erb
<br />
<%= render @link %>