config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root "home#index"

  devise_for :users, path: "",
             path_names: { sign_in: :login, sign_out: :logout, registration: :users },
             controllers: {
               sessions: "users/sessions",
               registrations: "users/registrations",
               passwords: "users/passwords",
             }

  resources :links
  resources :tags
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user

  has_many :taggings, :dependent => :destroy
  has_many :links, through: :taggings
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.includes(:links).where(user_id: current_user.id)
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)
    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: t('.notice') }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tags_path, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_path, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:name, :color).merge(user_id: current_user.id)
  end
end

app/controllers/v1/tags_controller.rb
class V1::TagsController < ApplicationController
  before_action :authenticate_v1_user!

  def index
    @tags = Gutentag::Tag.all
  end
end

app/views/tags/_form.html.erb
<%= simple_form_for @tag, html: { class: "col-md-6 col-sm-12 my-3" } do |f| %>

  <%= f.input :name, label: "이름" %>

  <%= f.input :color, as: :color, label: "색상" %>

  <div>
    <%= link_to "목록으로 돌아가기", tags_path, class: "btn btn-outline-secondary" %>
    <%= f.button :submit, "저장", class: "btn btn-outline-success" %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div class="col">
  <div class="card accordion" style="background-color: <%= tag.color %>">
    <div class="card-header accordion-button collapsed text-light" style="background-color: <%= tag.color %>"
         data-bs-toggle="collapse" data-bs-target="#accordion_<%= tag.id %>"
         aria-expanded="false" aria-controls="accordion_<%= tag.id %>">
      <%= tag.name %>
    </div>
    <ul id="accordion_<%= tag.id %>" class="list-group list-group-flush accordion-collapse collapse">
      <% tag.links.each do |link| %>
        <li class="list-group-item">
          <%= link_to link.name, link.url, target: "_blank", class: "link-dark" %>
        </li>
      <% end %>
    </ul>
    <div class="card-footer">
      <%= link_to "태그 수정", edit_tag_path(tag), class: "btn btn-outline-light" %>
      <%= link_to "태그 삭제", tag, class: "btn btn-outline-danger", data: { "turbo-method": :delete, "turbo-confirm": "정말로 삭제 하시나요?" } %>
    </div>
  </div>
</div>

app/views/tags/edit.html.erb
<h1 class="h3 my-3">태그 수정</h1>

<%= render "form", tag: @tag %>

app/views/tags/index.html.erb
<%= link_to "태그 추가", new_tag_path, class: "btn btn-outline-primary my-3" %>

<div class="row row-cols-1 row-cols-md-3 g-4 mb-3">
  <% @tags.each do |link| %>
    <%= render link %>
  <% end %>
</div>

app/views/tags/new.html.erb
<h1 class="h3 my-3">태그 생성</h1>

<%= render "form", tag: @tag %>

app/views/tags/show.html.erb
<br />
<%= render @tag %>